/*
 * facial recognition api
 * # Introducão  Seja bem-vindo a documentação da API de Reconhecimento Facial da [HIMNI.COM](https://himni.com)   Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de um [HTTP BEARER TOKEN](https://oauth.net/2/bearer-tokens/) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://face.himni.com.br/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.PersonGroupIdentify;
import io.swagger.client.model.PersonVerify;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RecognitionApi {
    private ApiClient apiClient;

    public RecognitionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RecognitionApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for personGroupIdentify
     * @param personGroupUuid  (required)
     * @param picture  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call personGroupIdentifyCall(String personGroupUuid, String picture, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/person-groups/{person_group_uuid}/identify"
            .replaceAll("\\{" + "person_group_uuid" + "\\}", apiClient.escapeString(personGroupUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (picture != null)
        localVarFormParams.put("picture", picture);

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "httpBearer" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call personGroupIdentifyValidateBeforeCall(String personGroupUuid, String picture, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'personGroupUuid' is set
        if (personGroupUuid == null) {
            throw new ApiException("Missing the required parameter 'personGroupUuid' when calling personGroupIdentify(Async)");
        }
        
        com.squareup.okhttp.Call call = personGroupIdentifyCall(personGroupUuid, picture, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Person Group - Identify
     * Identificação das correspondências mais próximas a uma imagem enviada, dentro de um Grupo de Pessoas. Será calculada a similaridade entre a imagem enviada e os modelos de reconhecimento facial cadastrados no Grupo de Pessoas, e será retornada uma listagem dos candidatos àquela Face ordenadas pelo índice de confiança.
     * @param personGroupUuid  (required)
     * @param picture  (optional)
     * @return List&lt;PersonGroupIdentify&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<PersonGroupIdentify> personGroupIdentify(String personGroupUuid, String picture) throws ApiException {
        ApiResponse<List<PersonGroupIdentify>> resp = personGroupIdentifyWithHttpInfo(personGroupUuid, picture);
        return resp.getData();
    }

    /**
     * Person Group - Identify
     * Identificação das correspondências mais próximas a uma imagem enviada, dentro de um Grupo de Pessoas. Será calculada a similaridade entre a imagem enviada e os modelos de reconhecimento facial cadastrados no Grupo de Pessoas, e será retornada uma listagem dos candidatos àquela Face ordenadas pelo índice de confiança.
     * @param personGroupUuid  (required)
     * @param picture  (optional)
     * @return ApiResponse&lt;List&lt;PersonGroupIdentify&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<PersonGroupIdentify>> personGroupIdentifyWithHttpInfo(String personGroupUuid, String picture) throws ApiException {
        com.squareup.okhttp.Call call = personGroupIdentifyValidateBeforeCall(personGroupUuid, picture, null, null);
        Type localVarReturnType = new TypeToken<List<PersonGroupIdentify>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Person Group - Identify (asynchronously)
     * Identificação das correspondências mais próximas a uma imagem enviada, dentro de um Grupo de Pessoas. Será calculada a similaridade entre a imagem enviada e os modelos de reconhecimento facial cadastrados no Grupo de Pessoas, e será retornada uma listagem dos candidatos àquela Face ordenadas pelo índice de confiança.
     * @param personGroupUuid  (required)
     * @param picture  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call personGroupIdentifyAsync(String personGroupUuid, String picture, final ApiCallback<List<PersonGroupIdentify>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = personGroupIdentifyValidateBeforeCall(personGroupUuid, picture, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<PersonGroupIdentify>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for personVerify
     * @param personUuid  (required)
     * @param picture  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call personVerifyCall(String personUuid, String picture, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/persons/{person_uuid}/verify"
            .replaceAll("\\{" + "person_uuid" + "\\}", apiClient.escapeString(personUuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (picture != null)
        localVarFormParams.put("picture", picture);

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "httpBearer" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call personVerifyValidateBeforeCall(String personUuid, String picture, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'personUuid' is set
        if (personUuid == null) {
            throw new ApiException("Missing the required parameter 'personUuid' when calling personVerify(Async)");
        }
        
        com.squareup.okhttp.Call call = personVerifyCall(personUuid, picture, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Person - Verify
     * Verifica se a imagem enviada corresponde à uma Pessoa específica.
     * @param personUuid  (required)
     * @param picture  (optional)
     * @return PersonVerify
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public PersonVerify personVerify(String personUuid, String picture) throws ApiException {
        ApiResponse<PersonVerify> resp = personVerifyWithHttpInfo(personUuid, picture);
        return resp.getData();
    }

    /**
     * Person - Verify
     * Verifica se a imagem enviada corresponde à uma Pessoa específica.
     * @param personUuid  (required)
     * @param picture  (optional)
     * @return ApiResponse&lt;PersonVerify&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<PersonVerify> personVerifyWithHttpInfo(String personUuid, String picture) throws ApiException {
        com.squareup.okhttp.Call call = personVerifyValidateBeforeCall(personUuid, picture, null, null);
        Type localVarReturnType = new TypeToken<PersonVerify>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Person - Verify (asynchronously)
     * Verifica se a imagem enviada corresponde à uma Pessoa específica.
     * @param personUuid  (required)
     * @param picture  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call personVerifyAsync(String personUuid, String picture, final ApiCallback<PersonVerify> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = personVerifyValidateBeforeCall(personUuid, picture, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<PersonVerify>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
